-- Generated Databricks Optimization Configuration SQL
-- Generated by: Python Automation Script

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_sap_journal_entries_raw',        -- tbl_name
    'finance_gl_bronze',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_journal_entries_cleaned',        -- tbl_name
    'finance_gl_silver',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_gl_balance_monthly_agg',        -- tbl_name
    'finance_gl_gold',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_crm_orders_raw',        -- tbl_name
    'sales_orders_bronze',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_order_header_cleaned',        -- tbl_name
    'sales_orders_silver',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_order_details_cleaned',        -- tbl_name
    'sales_orders_silver',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_sales_revenue_daily_agg',        -- tbl_name
    'sales_orders_gold',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_email_send_log_raw',        -- tbl_name
    'marketing_campaign_bronze',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_campaign_touchpoints',        -- tbl_name
    'marketing_campaign_silver',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_campaign_roi_analysis',        -- tbl_name
    'marketing_campaign_gold',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_wms_stock_levels_raw',        -- tbl_name
    'inventory_mgmt_bronze',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

INSERT INTO config_db.optimization_tasks (
    tbl_name,
    tbl_schema,
    ignore_partition,
    zorder_col,
    run_freq,
    rec_strt_ts,
    rec_end_ts,
    rec_flg,
    run_parallel_flg,
    non_partition_tables 
) VALUES (
    't_inventory_snapshot_daily',        -- tbl_name
    'inventory_mgmt_silver',       -- tbl_schema
    'Y',                   -- ignore_partition (defaulted)
    '',                    -- zorder_col (defaulted)
    'daily',               -- run_freq (defaulted)
    current_timestamp(),   -- rec_strt_ts
    '9999-12-31T00:00:00.000+0000', -- rec_end_ts (using UTC offset +0000 for generic example)
    'Y',                   -- rec_flg (defaulted)
    'Y',                   -- run_parallel_flg (defaulted)
    'group1'               -- non_partition_tables / grouping column (defaulted)
);

